version: 3

tasks:
  install:
    desc: Install
    cmds:
      - pnpm install && pnpm prune

  build:
    desc: Build
    deps: [ install ]
    cmds:
      - pnpm run build

  test:
    desc: Test
    deps: [ install ]
    cmds:
      - pnpm run test

  build-test-data-generator:
    dir: tools/test-data-generator
    cmds:
      - task build

  generateTestData:
    desc: Generate test data
    deps: [ build-test-data-generator ]
    cmds:
      - $TOOLDIR/bin/test-data-generator generateTestData --recursive testdata/basic build/testdata/basic
      - cp -r build/testdata/basic/* testdata/basic/
      - $TOOLDIR/bin/test-data-generator generateTestData --recursive --compare-reference serde-smile/tests build/testdata/serde-smile
      - rm -rf testdata/serde-smile
      - cp -r build/testdata/serde-smile testdata/serde-smile
    env:
      TOOLDIR: tools/test-data-generator/build/install/test-data-generator

  site-clean:
    desc: Clean site
    cmds:
      - rm -rf build/gh-pages

  site-build:
    desc: Build site
    cmds:
      - task: site-clean
      - mkdir -p build/gh-pages
      - task: site-build-mdbook
      - task: site-build-typedoc
      - task: site-build-example-html
      - task: site-build-example-svelte

  site-deploy:
    desc: Deploy site
    deps: [ site-build ]
    cmds:
      - gh-pages -d build/gh-pages --nojekyll

  site-build-mdbook:
    desc: Generate mdbook
    cmds:
      - mdbook build --dest-dir $(pwd)/build/gh-pages docs/mdbook

  site-build-typedoc:
    desc: Generate typedoc
    cmds:
      - pnpm run typedoc

  site-build-example-html:
    cmds:
      - mkdir -p build/gh-pages/examples/html
      - cp -r examples/html/* build/gh-pages/examples/html/

  site-build-example-svelte:
    deps: [ build-example-svelte ]
    cmds:
      - mkdir -p build/gh-pages/examples/svelte
      - cp -r examples/svelte/dist/* build/gh-pages/examples/svelte/

  build-example-svelte:
    desc: Build example
    dir: examples/svelte
    cmds:
      - pnpm install
      - pnpm run build
