name: Integration

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/basic

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run Example
        run: npm run example
